### ISSUE TITLE
Backwards Pass through spline.derivative gives nan gradients

### ISSUE THREAD

**Issue by kkadry** [patrick-kidger/torchcubicspline#11]
Hi there,
I'm using torchcubicspline as part of a larger optimization workflow where I'm finding the optimal parametric sampling points along a spline (1D vector that spans 0-1) to minimize a loss function. 
One part of my algorithm finds the tangent to each sampling point, and for some reason, the backwards pass sometimes returns nan gradients at this point during the spline.derivative function call.

Using torch.autograd.detect_anomaly,  i found that the problem is specifically in the following line:
![image](https://user-images.githubusercontent.com/84782148/151175830-32fd9a99-209c-4203-bfc9-bc8bae78c63c.png)
Where the error is:
![image](https://user-images.githubusercontent.com/84782148/151175906-e1bf442f-f074-42b5-9371-00b3a1c1f91b.png)
If you require any other information please let me know! The optimization code is a bit large, otherwise, I would have included a minimal code that reproduces the problem.
Thanks!

**Comment by patrick-kidger** [comment]
So I'm afraid without a minimal example to reproduce the problem it'll be difficult to pin this down.

**Comment by kkadry** [comment]
I'll see if I can try to create one in the next few weeks and open a new issue if I manage
Thank you for the response
