### ISSUE TITLE
Evaluating Each Spline at Unique Time Values in the Output Tensor

### ISSUE THREAD

**Issue by andidietsche** [patrick-kidger/torchcubicspline#16]
I Patrick, 
Great repo, 
I have a short question regarding the evaluation function. It returns the dim (batch, batch, time, time, and channel)
Is it possible to evaluate a different t for each spline and return that? Let's say I have 3 splines, and I want to assess each at a different t-value. At the moment, I always get an out-tensor where each spline gets evaluated with each t-value. However, I would like to have the first spline evaluated at the first t-value, and so on. 

Thank you

**Comment by patrick-kidger** [comment]
Unfortunately not.
If you're free to use JAX instead, and are happy with a slightly different kind of cubic spline (backward Hermite), then this functionality is available in [`diffrax.backward_hermite_coefficients`](https://docs.kidger.site/diffrax/api/interpolation/#diffrax.backward_hermite_coefficients). That's the best I can offer I'm afraid!

**Comment by andidietsche** [comment]
Thank you. I will have a look at Diffrax.
