### ISSUE TITLE
Differentiation with respect to coefficients

### ISSUE THREAD

**Issue by apisarek** [patrick-kidger/torchcubicspline#2]
Hi!

I would like to ask whether it's possible and what would be the best approach to use your implementation to differentiate with respect to coefficients and/or coordinates of interpolated points.

```import torch
from torchcubicspline import(natural_cubic_spline_coeffs, 
                             NaturalCubicSpline)

length, channels = 7, 3
t = torch.linspace(0, 1, length)
x = torch.rand(length, channels)
coeffs = natural_cubic_spline_coeffs(t, x)
spline = NaturalCubicSpline(coeffs)
point = torch.tensor(0.4)
out = spline.evaluate(point)
```

Looking at the provided simple example I would like to backpropagate from `out` to `x` - is it possible?

**Comment by patrick-kidger** [comment]
Yup, I think so - if I've written this correctly then everything should be differentiable. :)

**Comment by Gravifer** [comment]
I think this thread should be closed by now? Your work is for now by far the best solution for this problem! ;)

**Comment by patrick-kidger** [comment]
Yeah, it probably can. And thanks!
