### ISSUE TITLE
Complex value compatibility

### ISSUE THREAD

**Issue by StephenHogg** [patrick-kidger/torchcubicspline#9]
Hi,

Thanks for putting this together, it's a really useful bit of code. I wonder what it would take to make it compatible with complex dtypes? I'd be very grateful for any advice you could provide. Hope this isn't a bother.

Regards,

Stephen

**Comment by patrick-kidger** [comment]
I'm not sure. I haven't tried it with complex dtypes. If you find it has issues with complex dtypes then I'd be happy to accept a PR fixing such issues.
As a workaround you could also convert your complex data into real data, with twice the channels, pass it through the cubic spline code and then convert back again.

**Comment by StephenHogg** [comment]
Thanks, I'll look into doing that!
